openapi: 3.0.0
info:
  title: test
  description: test
  version: 0.0.1

paths:
  /api/user/askUsername:
    get:
      summary: Returns requested username.
      description: idk.
      responses:
        '200':    # status code
          description: JSON with account requested 
        '404': 
          description: no account found for requested userID
      parameters:
        - name: userID
          in: query
          required: true
          type: long